export const FIVE_PARAGRAPH_ESSAY_ID = 'five-paragraph-essay'
export const THESIS_ID = 'thesis'
export const COMMON_APP_ESSAY_ID = 'common-app-essay'
export const PERSUASIVE_ESSAY_ID = 'persuasive-essay'
export const EXPOSITORY_ESSAY_ID = 'expository-essay'
export const COMPARE_CONTRAST_ESSAY_ID = 'compare-contrast-essay'
