import { FilterMap, FilterType } from 'types'

export const tones = {
  accusatory: 'implying blame or wrongdoing',
  adoring: 'expressing admiration or affection',
  angry: 'feeling or showing annoyance',
  anxious: 'feeling worry or unease',
  ashamed: 'feeling embarrassed or guilty',
  blunt: 'direct and to the point, without beating around the bush',
  bold: 'confident and daring',
  boring: 'uninteresting and tedious',
  brisk: 'active, fast, and energetic',
  bubbly: 'cheerful and lively',
  burlesque: 'absurd or mocking imitation of something',
  calm: 'composed and unruffled',
  candid: 'straightforward and honest',
  casual: 'relaxed and unconcerned',
  cheerful: 'happy and optimistic',
  cliché:
    "a phrase that's been used so often it has lost its original meaning or impact",
  clinical: 'objective and detached, like a doctor or scientist',
  conceited: 'having an excessively favorable opinion of oneself',
  condescending: 'talking down to others in a patronizing way',
  curious: 'eager to learn or know something',
  depressed: 'feeling down or hopeless',
  desperate: 'urgently needing or wanting something',
  disturbed: 'marked by mental illness or instability',
  dramatic: 'intense and confrontational',
  eloquent: 'fluent and persuasive in speaking or writing',
  emotional: 'easily displaying or influenced by emotions',
  empathetic: 'able to understand and share the feelings of others',
  empowering: 'making someone more confident and capable',
  engaging: 'charming and attractive',
  expectant: 'showing anticipation or excitement for something to happen',
  familiar: 'well-known or commonly encountered',
  friendly: 'kind and pleasant',
  funny: 'causing amusement or laughter',
  furious: 'extremely angry',
  gentle: 'kind and considerate',
  helpful: 'offering assistance or support',
  hopeful: 'full of hope',
  hopeless: 'without hope',
  intimate: 'private or personal',
  lively: 'active and energetic',
  loving: 'showing deep concern or affection for someone or something',
  mysterious: 'puzzling or inexplicable',
  nervous: 'uneasy or anxious',
  nonchalant: 'unconcerned and indifferent',
  nostalgic: 'longing for past events or experiences',
  paranoid: 'showing irrational fear or suspicion',
  pedantic: 'overly concerned with minor details or rules',
  pessimistic: 'expecting the worst possible outcome',
  playful: 'lighthearted and humorous',
  powerful: 'showing great strength or influence',
  professional: 'qualified in a particular profession',
  psychotic: 'experiencing a loss of contact with reality',
  questioning: 'characterized by a desire to learn or understand',
  reassuring: "removing someone's doubts or fears",
  respectful: 'showing politeness or deference',
  satiric: 'exposing or criticizing something through ridicule or humor',
  scholarly: 'concerned with academic learning and research',
  serious: 'demanding careful consideration',
  vibrant: 'full of energy and enthusiasm',
  witty: 'clever and humorous in a verbal exchange',
  zealous: 'actively and passionately devoted to something',
}

export const languages = {
  Bulgarian: 'Bulgarian 🇧🇬',
  'Chinese (Simplified)': 'Chinese 🇨🇳 (Simplified)',
  'Chinese (Traditional)': 'Chinese 🇨🇳 (Traditional)',
  Czech: 'Czech 🇨🇿',
  Danish: 'Danish 🇩🇰',
  Dutch: 'Dutch 🇳🇱',
  English: 'English 🇺🇸',
  'English (British)': 'English (British) 🇬🇧',
  Estonian: 'Estonian 🇪🇪',
  Finnish: 'Finnish 🇫🇮',
  French: 'French 🇫🇷',
  German: 'German 🇩🇪',
  Greek: 'Greek 🇬🇷',
  Hungarian: 'Hungarian 🇭🇺',
  Indonesian: 'Indonesian 🇮🇩',
  Italian: 'Italian 🇮🇹',
  Japanese: 'Japanese 🇯🇵',
  Latvian: 'Latvian 🇱🇻',
  Lithuanian: 'Lithuanian 🇱🇹',
  Polish: 'Polish 🇵🇱',
  Portuguese: 'Portuguese 🇵🇹',
  'Portuguese (Brazilian)': 'Portuguese (Brazilian) 🇧🇷',
  Romanian: 'Romanian 🇷🇴',
  Russian: 'Russian 🇷🇺',
  Slovak: 'Slovak 🇸🇰',
  Slovenian: 'Slovenian 🇸🇮',
  Spanish: 'Spanish 🇪🇸',
  Swedish: 'Swedish 🇸🇪',
  Turkish: 'Turkish 🇹🇷',
  Ukrainian: 'Ukrainian 🇺🇦',
}

export const filters: FilterMap = {
  [FilterType.ESSAYS]: { text: 'Essays', selected: false },
  [FilterType.WRITING_TOOLS]: { text: 'Writing tools', selected: false },
  [FilterType.OTHER]: { text: 'Other', selected: false },
}
